const mongoose = require("mongoose");
require("dotenv").config();

const Quotes = [
  { quote: "Run into your unknown.", speaker: "Becs Gentry" },
  { quote: "The miracle isn’t that I finished. The miracle is that I had the courage to start.", speaker: "John Bingham" },
  { quote: "That’s the thing about running: your greatest runs are rarely measured by racing success. They are moments in time when running allows you to see how wonderful your life is.", speaker: "Kara Goucher" },
  { quote: "You didn’t get this far to only go this far.", speaker: "Ben Alldis" },
  { quote: "I don’t run to add days to my life, I run to add life to my days.", speaker: "Ronald Rook" },
  { quote: "Good things come slow—especially in distance running.", speaker: "Bill Dellinger" },
  { quote: "I often hear someone say, ‘I’m not a real runner.’ We are all runners, some just run faster than others. I never met a fake runner.", speaker: "Bart Yasso" },
  { quote: "Your mind is your strongest muscle.", speaker: "Tunde Oyeneyin" },
  { quote: "Run often. Run long. But never outrun your joy of running.", speaker: "Julie Isphording" },
  { quote: "Don’t dream of winning, train for it!", speaker: "Mo Farah" },
  { quote: "In running, it doesn’t matter whether you come in first, in the middle of the pack, or last. You can say, ‘I have finished.’ There is a lot of satisfaction in that.", speaker: "Fred Lebow" },
  { quote: "Take control of your workout and make the decision to succeed.", speaker: "Matt Wilpers" },
  { quote: "Whether a mile or a marathon, you get there the same way… one step at a time. Such is life.", speaker: "Baylor Barbee" },
  { quote: "The benefits and opportunities of running are available to anyone. You don’t have to be born a natural athlete, and you don’t have to be uniquely gifted. A life-shaping experience is there for the taking, waiting right outside your door.", speaker: "Donald Buraglio and Michael Dove" },
  { quote: "Fight fatigue with focus.", speaker: "Andy Speer" },
  { quote: "We are designed to run, and we increase our chance of daily happiness when we do so.", speaker: "Jeff Galloway" },
  { quote: "It’s very hard in the beginning to understand that the whole idea is not to beat the other runners. Eventually you learn that the competition is against the little voice inside you that wants you to quit.", speaker: "George Sheehan" },
  { quote: "I run because it’s so symbolic of life. You have to drive yourself to overcome the obstacles. You might feel that you can’t. But then you find your inner strength, and realize you’re capable of so much more than you thought.", speaker: "Arthur Blank" },
  { quote: "Don’t compare your chapter one with someone else’s chapter six.", speaker: "Ally Love" },
  { quote: "Running is the greatest metaphor for life, because you get out of it what you put into it.", speaker: "Oprah Winfrey" },
  { quote: "Our running shoes have magic in them. The power to transform a bad day into a good day; frustration into speed; self-doubt into confidence; chocolate cake into muscle.", speaker: "Mina Samuels" },
  { quote: "Fast running isn’t forced. You have to relax and let the run come out of you.", speaker: "Desiree Linden" },
  { quote: "You can’t be upset at the results you didn’t get for the work you didn’t do.", speaker: "Jess Sims" },
  { quote: "Never limit where running can take you. I mean that geographically, spiritually, and of course, physically.", speaker: "Bart Yasso" },
  { quote: "Every run is a work of art, a drawing on each day’s canvas. Some runs are shouts and some runs are whispers. Some runs are eulogies and others celebrations.", speaker: "Dagny Scott Barrios" },
  { quote: "If it doesn’t challenge you, it doesn’t change you.", speaker: "Fred DeVito" },
  { quote: "We all have bad days and bad workouts, when running gets ugly, when split times seem slow, when you wonder why you started. It will pass.", speaker: "Hal Higdon" },
  { quote: "You are truly your own hero in running. It is up to you to have the responsibility and self–discipline to get the job done.", speaker: "Adam Goucher" },
  { quote: "I’ve learned that it’s what you do with the miles, rather than how many you’ve run.", speaker: "Rod DeHaven" },
  { quote: "The pain you feel today will show itself as strength tomorrow.", speaker: "Tunde Oyeneyin" },
  { quote: "Mental will is a muscle that needs exercise, just like the muscles of the body.", speaker: "Lynn Jennings" },
  { quote: "It was being a runner that mattered, not how fast or how far I could run. The joy was in the act of running and in the journey, not in the destination.", speaker: "John Bingham" },
  { quote: "If your legs are tired, run with your heart!", speaker: "Tobias Heinze" },
  { quote: "Run often. Run long. But never outrun your joy of running.", speaker: "Kara Goucher" },
  { quote: "Set big goals and learn to love the work that gets you to them.", speaker: "Des Linden" },
  { quote: "I breathe in strength and breathe out weakness.", speaker: "Amy Hastings Cragg" },
  { quote: "Never underestimate the power that one good workout will have on your mind. Keeping the dream alive is half the battle.", speaker: "Kara Goucher" },
  { quote: "It’s good to be uncomfortable. Lean into it. One effort at a time. That’s when you will start to grow and surprise yourself.", speaker: "Becca Jay" },
  { quote: "One run can change your day, many runs can change your life.", speaker: "Unknown" },
  { quote: "Run happy.", speaker: "Unknown" },
  { quote: "Just keep moving.", speaker: "Unknown" },
  { quote: "Miles equal smiles.", speaker: "Unknown" },
  { quote: "Don’t dream of winning, train for it!", speaker: "Mo Farah" },
  { quote: "The only bad run is the one that didn’t happen.", speaker: "Unknown" },
  { quote: "What seems hard now will one day be your warm‑up.", speaker: "Unknown" },
  { quote: "You don’t run because you have to, run because you can.", speaker: "Unknown" }
];

module.exports = Quotes;
